# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Common metadata that is in shared among work models. This includes Hyrax's
# basic metadata that is in common as well as custom common terms. (Customizations
# may have been made to Hyrax's metadata)

attributes:
  relative_path:
    type: string
    predicate: http://scholarsphere.psu.edu/ns#relativePath
  related_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "related_url_sim"
      - "related_url_tesim"
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
  resource_type:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "resource_type_sim"
      - "resource_type_tesim"
    predicate: http://purl.org/dc/terms/type
  rights_notes:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "rights_notes_sim"
      - "rights_notes_tesim"
    predicate: http://purl.org/dc/elements/1.1/rights
  rights_statement:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "rights_statement_sim"
      - "rights_statement_tesim"
    predicate: http://www.europeana.eu/schemas/edm/rights
  source:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "source_sim"
      - "source_tesim"
    predicate: http://purl.org/dc/terms/source
  subject:
    type: string
    multiple: true
    index_keys:
      - "subject_sim"
      - "subject_tesim"
    form:
      primary: false
    predicate: http://purl.org/dc/elements/1.1/subject
