# This file is blank to override base Hyku
# Each model will have its own model resource metadata.yaml
# that includes basic metadata for more customizations

attributes:
  based_near:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "based_near_sim"
      - "based_near_tesim"
    predicate: http://xmlns.com/foaf/0.1/based_near
