attributes:
  keyword:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - keyword_tesim
    - keyword_sim
    predicate: http://purl.org/dc/elements/1.1/relation
  date:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - date_tesim
    - date_sim
    predicate: http://purl.org/dc/terms/date
  date_available:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_available_tesim
    - date_available_sim
    predicate: http://purl.org/dc/terms/available
  date_published:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_published_tesim
    - date_published_sim
    predicate: http://schema.org/datePublished
  date_submitted:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_submitted_tesim
    - date_submitted_sim
    predicate: http://london.ac.uk/ontologies/terms#dateSubmitted
  date_accepted:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_accepted_tesim
    - date_accepted_sim
    predicate: http://purl.org/dc/terms/dateAccepted
  date_issued:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_issued_tesim
    - date_issued_sim
    predicate: http://purl.org/dc/terms/issued
  doi:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - doi_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/doi
  former_identifier:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - former_identifier_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#formerIdentifier
  funder:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - funder_tesim
    - funder_sim
    predicate: http://id.loc.gov/vocabulary/relators/fnd
  issue_number:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - issue_number_tesim
    predicate: http://schema.org/issueNumber
  location:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - location_tesim
    - location_sim
    predicate: http://schema.org/location
  managing_organisation:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - managing_organisation_tesim
    - managing_organisation_sim
    predicate: http://dlib.york.ac.uk/ontologies/pure#pureManagingUnit
  note:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - note_tesim
    predicate: http://www.w3.org/2004/02/skos/core#note
  official_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - official_url_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/uri
  orcid:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - orcid_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/orcid
  output_of:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - output_of_tesim
    - output_of_sim
    predicate: http://purl.org/cerif/frapo/isOutputOf
  pagination:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - pagination_tesim
    predicate: http://schema.org/pagination
  part_of:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - part_of_tesim
    - part_of_sim
    predicate: http://id.loc.gov/ontologies/bibframe/partOf
  publication_status:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - publication_status_tesim
    - publication_status_sim
    predicate: http://purl.org/ontology/bibo/status
  place_of_publication:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - place_of_publication_tesim
    predicate: http://id.loc.gov/vocabulary/relators/pup
  refereed:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - refereed_tesim
    - refereed_sim
    predicate: http://london.ac.uk/ontologies/terms#refereed
  remote_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - remote_url_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/uri
  rights_holder:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - rights_holder_tesim
    predicate: http://purl.org/dc/terms/rightsHolder
  rights_description:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - rights_description_tesim
    predicate: http://purl.org/dc/elements/1.1/rights
  preflabel:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - preflabel_tesim
    - preflabel_si
    predicate: http://www.w3.org/2004/02/skos/core#prefLabel
  altlabel:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - altlabel_tesim
    predicate: http://www.w3.org/2004/02/skos/core#altLabel
  volume_number:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - volume_number_tesim
    predicate: http://schema.org/volumeNumber
