# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource DatasetResource`

attributes:
  date_published:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_published_tesim
    - date_published_sim
    predicate: http://schema.org/datePublished
  resource_type_general:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - resource_type_general_tesim
    predicate: http://purl.org/spar/datacite/hasGeneralResourceType
  date_collected:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_collected_tesim
    - date_collected_sim
    predicate: http://purl.org/spar/fabio/hasDateCollected
  date_issued:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_issued_tesim
    - date_issued_sim
    predicate: http://purl.org/dc/terms/issued
  keyword:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - keyword_tesim
    - keyword_sim
    predicate: http://schema.org/keywords
  dc_format:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - dc_format_tesim
    predicate: http://purl.org/dc/elements/1.1/format
  extent:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - extent_tesim
    predicate: http://purl.org/dc/terms/extent
  dc_access_rights:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - dc_access_rights_tesim
    predicate: http://purl.org/dc/terms/accessRights
  date_accepted:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_accepted_tesim
    - date_accepted_sim
    predicate: http://purl.org/dc/terms/dateAccepted
  date_copyrighted:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_copyrighted_tesim
    - date_copyrighted_sim
    predicate: http://purl.org/dc/terms/dateCopyrighted
  content_version:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - content_version_tesim
    - content_version_sim
    predicate: http://schema.org/version
  date_available:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_available_tesim
    - date_available_sim
    predicate: http://purl.org/dc/terms/available
  date_submitted:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_submitted_tesim
    - date_submitted_sim
    predicate: http://london.ac.uk/ontologies/terms#dateSubmitted
  for_indexing:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - for_indexing_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#forIndexing
  has_restriction:
    type: date_time
    multiple: true
    form:
      primary: false
    index_keys:
    - has_restriction_tesim
    predicate: http://www.loc.gov/premis/rdf/v1#hasRestriction
  date_valid:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_valid_tesim
    - date_valid_sim
    predicate: http://www.loc.gov/mods/rdf/v1#dateValid
  number_of_downloads:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - number_of_downloads_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#numberOfDownloads
  readme:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - readme_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#readme
  requestor_email:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - requestor_email_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#requestorEmail
  subtitle:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - subtitle_tesim
    - subtitle_sim
    predicate: http://id.loc.gov/ontologies/bibframe/subtitle
  date_updated:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_updated_tesim
    - date_updated_sim
    predicate: http://schema.org/dateModified
  last_access:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - last_access_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#lastAccess
# basic_metadata
  abstract:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "abstract_sim"
      - "abstract_tesim"
    predicate: http://purl.org/dc/terms/abstract
  access_right:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "access_right_sim"
      - "access_right_tesim"
    predicate: http://purl.org/dc/terms/accessRights
  # slugs previously used same predicate
  alternative_title:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "alternative_title_sim"
      - "alternative_title_tesim"
    predicate: http://purl.org/dc/terms/alternative
  arkivo_checksum:
    type: string
    multiple: false
    form:
      primary: false
    predicate: http://scholarsphere.psu.edu/ns#arkivoChecksum
  based_near:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "based_near_sim"
      - "based_near_tesim"
    predicate: http://xmlns.com/foaf/0.1/based_near
  bibliographic_citation:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "bibliographic_citation_sim"
      - "bibliographic_citation_tesim"
    predicate: http://purl.org/dc/terms/bibliographicCitation
  contributor:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "contributor_tesim"
      - "contributor_sim"
    predicate: http://purl.org/dc/elements/1.1/contributor
  creator:
    type: string
    multiple: true
    form:
      required: false
      primary: false
    index_keys:
      - "creator_sim"
      - "creator_tesim"
    predicate: http://purl.org/dc/elements/1.1/creator
  date_created:
    type: date_time
    multiple: true
    form:
      primary: false
    index_keys:
      - "date_created_sim"
      - "date_created_tesim"
    predicate: http://purl.org/dc/terms/created
  description:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "description_sim"
      - "description_tesim"
    predicate: http://purl.org/dc/elements/1.1/description
  identifier:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "identifier_sim"
      - "identifier_tesim"
    predicate: http://purl.org/dc/terms/identifier
  import_url:
    type: string
    predicate: http://scholarsphere.psu.edu/ns#importUrl
  # Comment out - left in each model's yaml... predicates vary among work models
  # keyword:
  #   type: string
  #   multiple: true
  #   index_keys:
  #     - "keyword_sim"
  #     - "keyword_tesim"
  #   form:
  #     primary: false
  #   predicate: http://schema.org/keywords
  publisher:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "publisher_sim"
      - "publisher_tesim"
    predicate: http://purl.org/dc/elements/1.1/publisher
  label:
    type: string
    form:
      primary: false
    index_keys:
      - "label_sim"
      - "label_tesim"
    predicate: info:fedora/fedora-system:def/model#downloadFilename
  language:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "language_sim"
      - "language_tesim"
    predicate: http://purl.org/dc/elements/1.1/language
  # Override because nonstandard predicate
  license:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - license_tesim
    predicate: http://purl.org/dc/terms/rights
  relative_path:
    type: string
    predicate: http://scholarsphere.psu.edu/ns#relativePath
  related_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "related_url_sim"
      - "related_url_tesim"
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
  resource_type:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "resource_type_sim"
      - "resource_type_tesim"
    predicate: http://purl.org/dc/terms/type
  rights_notes:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "rights_notes_sim"
      - "rights_notes_tesim"
    predicate: http://purl.org/dc/elements/1.1/rights
  # nonstandard definition: multiple false, required true
  rights_statement:
    type: string
    multiple: false
    form:
      required: true
      primary: true
    index_keys:
    - rights_statement_tesim
    - rights_statement_sim
    predicate: http://www.europeana.eu/schemas/edm/rights
  source:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "source_sim"
      - "source_tesim"
    predicate: http://purl.org/dc/terms/source
  subject:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
      - "subject_sim"
      - "subject_tesim"
    predicate: http://purl.org/dc/elements/1.1/subject
  long:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - long_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#long
  lat:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - lat_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#lat
  alt:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - alt_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#alt
  owner:
    type: string
    multiple: false
    form:
      primary: false
    predicate: http://opaquenamespace.org/ns/hydra/owner
  on_behalf_of:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - on_behalf_of_ssim
    predicate: http://scholarsphere.psu.edu/ns#onBehalfOf
  state:
    type: string
    multiple: false
    form:
      primary: false
    predicate: http://fedora.info/definitions/1/0/access/ObjState#objState
  proxy_depositor:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - proxy_depositor_ssim
    predicate: http://scholarsphere.psu.edu/ns#proxyDepositor
