# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource DatasetResource`

attributes:
  rights_statement:
    type: string
    multiple: false
    form:
      required: true
      primary: true
      multiple: false
    index_keys:
    - rights_statement_tesim
    - rights_statement_sim
  access_right:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  rights_notes:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  bibliographic_citation:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - bibliographic_citation_tesim
  creator:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - creator_tesim
    - creator_si
    - creator_sim
  publisher:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - publisher_tesim
    - publisher_si
    - publisher_sim
  date_published:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_published_tesim
    - date_published_sim
    - date_published_ssi
  resource_type_general:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - resource_type_general_tesim
    - resource_type_general_si
  resource_type:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - resource_type_tesim
    - resource_type_si
  abstract:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - abstract_tesim
    - abstract_si
  contributor:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - contributor_tesim
    - contributor_si
    - contributor_sim
  funder:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - funder_tesim
    - funder_sim
  output_of:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - output_of_tesim
    - output_of_sim
  date_collected:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_collected_tesim
    - date_collected_sim
    - date_collected_ssi
    - date_collected_si
  date_created:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_created_tesim
    - date_created_sim
    - date_created_ssi
  date_issued:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_issued_tesim
    - date_issued_sim
    - date_issued_ssi
  doi:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - doi_tesim
  identifier:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - identifier_tesim
    - identifier_si
  subject:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - subject_tesim
    - subject_sim
  keyword:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - keyword_tesim
    - keyword_sim
  language:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - language_tesim
    - language_si
    - language_sim
  based_near:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  dc_format:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - dc_format_tesim
  extent:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - extent_tesim
  related_url:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - related_url_tesim
  license:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - license_tesim
  source:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - source_tesim
  aark_id:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - aark_id_tesim
  description:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - description_tesim
    - description_si
  dc_access_rights:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - dc_access_rights_tesim
  date_accepted:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_accepted_tesim
    - date_accepted_sim
    - date_accepted_ssi
  content_version:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - content_version_tesim
    - content_version_sim
  slug:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - slug_tesim
  slug_for_upgrade:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - slug_for_upgrade_tesim
  date_available:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_available_tesim
    - date_available_sim
    - date_available_ssi
    - date_available_si
  date_submitted:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_submitted_tesim
    - date_submitted_sim
    - date_submitted_ssi
  date_updated:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_updated_tesim
    - date_updated_sim
    - date_updated_ssi
  date_valid:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_valid_tesim
    - date_valid_sim
  date_copyrighted:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_copyrighted_tesim
    - date_copyrighted_sim
    - date_copyrighted_ssi
  import_url:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - import_url_ssim
  label:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
  arkivo_checksum:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
  alternative_title:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  relative_path:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
  for_indexing:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - for_indexing_tesim
  number_of_downloads:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - number_of_downloads_tesim
  readme:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - readme_tesim
  requestor_email:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - requestor_email_tesim
  has_restriction:
    type: date_time
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - has_restriction_tesim
  preflabel:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - preflabel_tesim
    - preflabel_si
  altlabel:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - altlabel_tesim
  rdfs_label:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - rdfs_label_tesim
  rights_holder:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - rights_holder_tesim
  rights_description:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - rights_description_tesim
  last_access:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - last_access_tesim
  subtitle:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - subtitle_tesim
    - subtitle_sim
  date:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - date_tesim
    - date_sim
    - date_ssi
  language_code:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - language_code_tesim
  department:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - department_tesim
    - department_sim
  lat:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - lat_tesim
  long:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - long_tesim
  alt:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - alt_tesim
  location:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - location_tesim
    - location_sim
  managing_organisation:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - managing_organisation_tesim
    - managing_organisation_sim
  note:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - note_tesim
  former_identifier:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - former_identifier_tesim
