# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource DatasetResource`

attributes:
  date_published:
    type: string
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_published_tesim
    - date_published_sim
    predicate: http://schema.org/datePublished
  resource_type_general:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - resource_type_general_tesim
    predicate: http://purl.org/spar/datacite/hasGeneralResourceType
  date:
    type: string
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_tesim
    - date_sim
    predicate: http://purl.org/dc/terms/date
  date_collected:
    type: date_time
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_collected_tesim
    - date_collected_sim
    predicate: http://purl.org/spar/fabio/hasDateCollected
  date_issued:
    type: date_time
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_issued_tesim
    - date_issued_sim
    predicate: http://purl.org/dc/terms/issued
  keyword:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - keyword_tesim
    - keyword_sim
    predicate: http://schema.org/keywords
  dc_format:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - dc_format_tesim
    predicate: http://purl.org/dc/elements/1.1/format
  extent:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - extent_tesim
    predicate: http://purl.org/dc/terms/extent
  date_accepted:
    type: string
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_accepted_tesim
    - date_accepted_sim
    predicate: http://purl.org/dc/terms/dateAccepted
  date_copyrighted:
    type: date_time
    multiple: true
    form:
      primary: false
      multiple: true
    index_keys:
    - date_copyrighted_tesim
    - date_copyrighted_sim
    predicate: http://purl.org/dc/terms/dateCopyrighted
  content_version:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - content_version_tesim
    - content_version_sim
    predicate: http://schema.org/version
  date_available:
    type: date_time
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_available_tesim
    - date_available_sim
    predicate: http://purl.org/dc/terms/available
  date_submitted:
    type: string
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_submitted_tesim
    - date_submitted_sim
    predicate: http://london.ac.uk/ontologies/terms#dateSubmitted
  for_indexing:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - for_indexing_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#forIndexing
  has_restriction:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - has_restriction_tesim
    predicate: http://www.loc.gov/premis/rdf/v1#hasRestriction
  date_valid:
    type: string
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_valid_tesim
    - date_valid_sim
    predicate: http://www.loc.gov/mods/rdf/v1#dateValid
  number_of_downloads:
    type: string
    multiple: false
    form:
      primary: false
      multiple: false
    index_keys:
    - number_of_downloads_tesi
    predicate: http://dlib.york.ac.uk/ontologies/generic#numberOfDownloads
  readme:
    type: string
    multiple: false
    form:
      primary: false
      multiple: false
    index_keys:
    - readme_tesi
    predicate: http://dlib.york.ac.uk/ontologies/generic#readme
  requestor_email:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - requestor_email_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#requestorEmail
  subtitle:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - subtitle_tesim
    - subtitle_sim
    predicate: http://id.loc.gov/ontologies/bibframe/subtitle
  date_updated:
    type: string
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_updated_tesim
    - date_updated_sim
    predicate: http://schema.org/dateModified
  last_access:
    type: date_time
    multiple: false
    form:
      primary: false
      multiple: false
    index_keys:
    - last_access_tesi
    predicate: http://dlib.york.ac.uk/ontologies/generic#lastAccess
