# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource DatasetResource`

attributes:
  rights_statement:
    type: string
    multiple: false
    form:
      required: true
      primary: true
      multiple: false
    index_keys:
    - rights_statement_tesim
    - rights_statement_sim
    predicate: http://www.europeana.eu/schemas/edm/rights
  rights_notes:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/elements/1.1/rights
  date_published:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_published_tesim
    - date_published_sim
    - date_published_ssi
    predicate: http://schema.org/datePublished
  resource_type_general:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - resource_type_general_tesim
    - resource_type_general_si
    predicate: http://purl.org/spar/datacite/hasGeneralResourceType
  resource_type:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - resource_type_tesim
    - resource_type_si
    predicate: http://purl.org/dc/terms/type
  funder:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - funder_tesim
    - funder_sim
    predicate: http://id.loc.gov/vocabulary/relators/fnd
  output_of:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - output_of_tesim
    - output_of_sim
    predicate: http://purl.org/cerif/frapo/isOutputOf
  date_collected:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_collected_tesim
    - date_collected_sim
    - date_collected_ssi
    - date_collected_si
    predicate: http://purl.org/spar/fabio/hasDateCollected
  date_issued:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_issued_tesim
    - date_issued_sim
    - date_issued_ssi
    predicate: http://purl.org/dc/terms/issued
  doi:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - doi_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/doi
  subject:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - subject_tesim
    - subject_sim
    predicate: http://purl.org/dc/elements/1.1/subject
  keyword:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - keyword_tesim
    - keyword_sim
    predicate: http://schema.org/keywords
  dc_format:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - dc_format_tesim
    predicate: http://purl.org/dc/elements/1.1/format
  extent:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - extent_tesim
    predicate: http://purl.org/dc/terms/extent
  related_url:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - related_url_tesim
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
  license:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - license_tesim
    predicate: http://purl.org/dc/terms/rights
  source:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - source_tesim
    predicate: http://purl.org/dc/terms/source
  owner:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://opaquenamespace.org/ns/hydra/owner
  dc_access_rights:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - dc_access_rights_tesim
    predicate: http://purl.org/dc/terms/accessRights
  date_accepted:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_accepted_tesim
    - date_accepted_sim
    - date_accepted_ssi
    predicate: http://purl.org/dc/terms/dateAccepted
  date_copyrighted:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_copyrighted_tesim
    - date_copyrighted_sim
    - date_copyrighted_ssi
    predicate: http://purl.org/dc/terms/dateCopyrighted
  content_version:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - content_version_tesim
    - content_version_sim
    predicate: http://schema.org/version
  date_available:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_available_tesim
    - date_available_sim
    - date_available_ssi
    - date_available_si
    predicate: http://purl.org/dc/terms/available
  on_behalf_of:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - on_behalf_of_ssim
    predicate: http://scholarsphere.psu.edu/ns#onBehalfOf
  state:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://fedora.info/definitions/1/0/access/ObjState#objState
  proxy_depositor:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - proxy_depositor_ssim
    predicate: http://scholarsphere.psu.edu/ns#proxyDepositor
  relative_path:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    predicate: http://scholarsphere.psu.edu/ns#relativePath
  date_submitted:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_submitted_tesim
    - date_submitted_sim
    - date_submitted_ssi
    predicate: http://london.ac.uk/ontologies/terms#dateSubmitted
  for_indexing:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - for_indexing_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#forIndexing
  has_restriction:
    type: date_time
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - has_restriction_tesim
    predicate: http://www.loc.gov/premis/rdf/v1#hasRestriction
  date_valid:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_valid_tesim
    - date_valid_sim
    predicate: http://www.loc.gov/mods/rdf/v1#dateValid
  number_of_downloads:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - number_of_downloads_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#numberOfDownloads
  readme:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - readme_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#readme
  requestor_email:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - requestor_email_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#requestorEmail
  subtitle:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - subtitle_tesim
    - subtitle_sim
    predicate: http://id.loc.gov/ontologies/bibframe/subtitle
  preflabel:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - preflabel_tesim
    - preflabel_si
    predicate: http://www.w3.org/2004/02/skos/core#prefLabel
  date_updated:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_updated_tesim
    - date_updated_sim
    - date_updated_ssi
    predicate: http://schema.org/dateModified
  last_access:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - last_access_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#lastAccess
  altlabel:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - altlabel_tesim
    predicate: http://www.w3.org/2004/02/skos/core#altLabel
  rights_holder:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - rights_holder_tesim
    predicate: http://purl.org/dc/terms/rightsHolder
  date:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - date_tesim
    - date_sim
    - date_ssi
    predicate: http://purl.org/dc/terms/date
  rdfs_label:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - rdfs_label_tesim
    predicate: http://www.w3.org/2000/01/rdf-schema#label
  rights_description:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - rights_description_tesim
    predicate: http://purl.org/dc/elements/1.1/rights
  department:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - department_tesim
    - department_sim
    predicate: http://schema.org/department
  language_code:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - language_code_tesim
    predicate: http://purl.org/dc/terms/language
  lat:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - lat_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#lat
  long:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - long_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#long
  alt:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - alt_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#alt
  location:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - location_tesim
    - location_sim
    predicate: http://schema.org/location
  managing_organisation:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - managing_organisation_tesim
    - managing_organisation_sim
    predicate: http://dlib.york.ac.uk/ontologies/pure#pureManagingUnit
  note:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - note_tesim
    predicate: http://www.w3.org/2004/02/skos/core#note
  former_identifier:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - former_identifier_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#formerIdentifier
