# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource ExamPaperResource`

attributes:
  rights_statement:
    type: string
    multiple: false
    form:
      required: true
      primary: true
      multiple: false
    index_keys:
    - rights_statement_tesim
    - rights_statement_sim
  access_right:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  rights_notes:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  bibliographic_citation:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - bibliographic_citation_tesim
  creator:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - creator_tesim
    - creator_si
    - creator_sim
  publisher:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - publisher_tesim
    - publisher_si
    - publisher_sim
  resource_type:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - resource_type_tesim
    - resource_type_si
  abstract:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  contributor:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - contributor_tesim
    - contributor_si
    - contributor_sim
  funder:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - funder_tesim
    - funder_sim
  output_of:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - output_of_tesim
    - output_of_sim
  date_created:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_created_tesim
    - date_created_sim
    - date_created_ssi
  doi:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - doi_tesim
  identifier:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - identifier_tesim
    - identifier_si
  subject:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - subject_tesim
    - subject_sim
  keyword:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - keyword_tesim
    - keyword_sim
  language:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - language_tesim
    - language_si
    - language_sim
  based_near:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  related_url:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - related_url_tesim
  license:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - license_tesim
  source:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - source_tesim
  aark_id:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - aark_id_tesim
  relative_path:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
  alternative_title:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
  arkivo_checksum:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
  label:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
  slug_for_upgrade:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - slug_for_upgrade_tesim
  slug:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - slug_tesim
  qualification_name:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - qualification_name_tesim
    - qualification_name_sim
  module_code:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - module_code_tesim
  date_available:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_available_tesim
    - date_available_sim
    - date_available_ssi
    - date_available_si
  preflabel:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - preflabel_tesim
    - preflabel_si
  altlabel:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - altlabel_tesim
  qualification_level:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - qualification_level_tesim
    - qualification_level_sim
  rdfs_label:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - rdfs_label_tesim
  rights_description:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - rights_description_tesim
  rights_holder:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - rights_holder_tesim
  department:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - department_tesim
    - department_sim
  date:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - date_tesim
    - date_sim
    - date_ssi
  language_code:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - language_code_tesim
  import_url:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - import_url_ssim
  description:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - description_tesim
    - description_si
  lat:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - lat_tesim
  long:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - long_tesim
  alt:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - alt_tesim
  location:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - location_tesim
    - location_sim
  managing_organisation:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - managing_organisation_tesim
    - managing_organisation_sim
  note:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - note_tesim
  former_identifier:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - former_identifier_tesim
