# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource ExamPaperResource`

attributes:
  keyword:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - keyword_tesim
    - keyword_sim
    predicate: http://schema.org/keywords
  date:
    type: string
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_tesim
    - date_sim
    predicate: http://purl.org/dc/terms/date
  module_code:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - module_code_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#moduleCode
  qualification_name:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - qualification_name_tesim
    - qualification_name_sim
    predicate: http://dlib.york.ac.uk/ontologies/uketd#qualificationName
  qualification_level:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - qualification_level_tesim
    - qualification_level_sim
    predicate: http://dlib.york.ac.uk/ontologies/uketd#qualificationLevel
  date_available:
    type: date_time
    multiple: true
    form:
      primary: false
      multiple: false
    index_keys:
    - date_available_tesim
    - date_available_sim
    predicate: http://purl.org/dc/terms/available
