# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource JournalArticleResource`

attributes:
  date_published:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_published_tesim
    - date_published_sim
    predicate: http://schema.org/datePublished
  date_issued:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_issued_tesim
    - date_issued_sim
    predicate: http://purl.org/dc/terms/issued
  keyword:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - keyword_tesim
    - keyword_sim
    predicate: http://schema.org/keywords
  place_of_publication:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - place_of_publication_tesim
    predicate: http://id.loc.gov/vocabulary/relators/pup
  remote_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - remote_url_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/uri
  date_available:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_available_tesim
    - date_available_sim
    predicate: http://purl.org/dc/terms/available
  date_submitted:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_submitted_tesim
    - date_submitted_sim
    predicate: http://london.ac.uk/ontologies/terms#dateSubmitted
  date_accepted:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - date_accepted_tesim
    - date_accepted_sim
    predicate: http://purl.org/dc/terms/dateAccepted
  orcid:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - orcid_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/orcid
  part_of:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - part_of_tesim
    - part_of_sim
    predicate: http://id.loc.gov/ontologies/bibframe/partOf
  publication_status:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - publication_status_tesim
    - publication_status_sim
    predicate: http://purl.org/ontology/bibo/status
  refereed:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - refereed_tesim
    - refereed_sim
    predicate: http://london.ac.uk/ontologies/terms#refereed
  issue_number:
    type: string
    multiple: false
    form:
      primary: false
    index_keys:
    - issue_number_tesim
    predicate: http://schema.org/issueNumber
  official_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - official_url_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/uri
  pagination:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - pagination_tesim
    predicate: http://schema.org/pagination
  volume_number:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - volume_number_tesim
    predicate: http://schema.org/volumeNumber
