# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource ThesisResource`

attributes:
  date_issued:
    type: date_time
    multiple: false
    form:
      primary: false
    index_keys:
    - date_issued_tesi
    - date_issued_si
    predicate: http://purl.org/dc/terms/issued
  keyword:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - keyword_tesim
    - keyword_sim
    predicate: http://schema.org/keywords
  extent:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - extent_tesim
    predicate: http://purl.org/dc/terms/extent
  part_of:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - part_of_tesim
    - part_of_sim
    predicate: http://id.loc.gov/ontologies/bibframe/partOf
  place_of_publication:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - place_of_publication_tesim
    predicate: http://id.loc.gov/vocabulary/relators/pup
  remote_url:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - remote_url_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/uri
  advisor:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - advisor_tesim
    - advisor_sim
    predicate: http://id.loc.gov/vocabulary/relators/ths
  orcid:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - orcid_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/orcid
  date_of_award:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - date_of_award_tesim
    - date_of_award_sim
    predicate: http://purl.org/dc/terms/dateAccepted
  qualification_level:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - qualification_level_tesim
    - qualification_level_sim
    predicate: http://dlib.york.ac.uk/ontologies/uketd#qualificationLevel
  awarding_institution:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - awarding_institution_tesim
    - awarding_institution_sim
    predicate: http://id.loc.gov/ontologies/bibframe/grantingInstitution
  qualification_name:
    type: string
    multiple: true
    form:
      primary: false
    index_keys:
    - qualification_name_tesim
    - qualification_name_sim
    predicate: http://dlib.york.ac.uk/ontologies/uketd#qualificationName
