# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource ThesisResource`

attributes:
  rights_statement:
    type: string
    multiple: false
    form:
      required: true
      primary: true
      multiple: false
    index_keys:
    - rights_statement_tesim
    - rights_statement_sim
    predicate: http://www.europeana.eu/schemas/edm/rights
  access_right:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    predicate: http://purl.org/dc/terms/accessRights
  rights_notes:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    predicate: http://purl.org/dc/elements/1.1/rights
  bibliographic_citation:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    predicate: http://purl.org/dc/terms/bibliographicCitation
  creator:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - creator_tesim
    - creator_si
    - creator_sim
    predicate: http://purl.org/dc/elements/1.1/creator
  publisher:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - publisher_tesim
    - publisher_si
    - publisher_sim
    predicate: http://purl.org/dc/elements/1.1/publisher
  resource_type:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - resource_type_tesim
    - resource_type_si
    predicate: http://purl.org/dc/terms/type
  abstract:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - abstract_tesim
    - abstract_si
    predicate: http://purl.org/dc/terms/abstract
  contributor:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - contributor_tesim
    - contributor_si
    - contributor_sim
    predicate: http://purl.org/dc/elements/1.1/contributor
  funder:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - funder_tesim
    - funder_sim
    predicate: http://id.loc.gov/vocabulary/relators/fnd
  output_of:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - output_of_tesim
    - output_of_sim
    predicate: http://purl.org/cerif/frapo/isOutputOf
  date_created:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_created_tesim
    - date_created_sim
    - date_created_ssi
    predicate: http://purl.org/dc/terms/created
  date_issued:
    type: date_time
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - date_issued_tesim
    - date_issued_sim
    - date_issued_ssi
    predicate: http://purl.org/dc/terms/issued
  doi:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - doi_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/doi
  identifier:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - identifier_tesim
    - identifier_si
    predicate: http://purl.org/dc/terms/identifier
  subject:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - subject_tesim
    - subject_sim
    predicate: http://purl.org/dc/elements/1.1/subject
  keyword:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - keyword_tesim
    - keyword_sim
    predicate: http://schema.org/keywords
  language:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - language_tesim
    - language_si
    - language_sim
    predicate: http://purl.org/dc/elements/1.1/language
  based_near:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    predicate: http://xmlns.com/foaf/0.1/based_near
  extent:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - extent_tesim
    predicate: http://purl.org/dc/terms/extent
  related_url:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - related_url_tesim
    predicate: http://www.w3.org/2000/01/rdf-schema#seeAlso
  license:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - license_tesim
    predicate: http://purl.org/dc/terms/rights
  source:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - source_tesim
    predicate: http://purl.org/dc/terms/source
  description:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - description_tesim
    - description_si
    predicate: http://purl.org/dc/elements/1.1/description
  import_url:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - import_url_ssim
    predicate: http://scholarsphere.psu.edu/ns#importUrl
  label:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    predicate: info:fedora/fedora-system:def/model#downloadFilename
  alternative_title:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    predicate: http://purl.org/dc/terms/alternative
  relative_path:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    predicate: http://scholarsphere.psu.edu/ns#relativePath
  part_of:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - part_of_tesim
    - part_of_sim
    predicate: http://id.loc.gov/ontologies/bibframe/partOf
  long:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - long_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#long
  lat:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - lat_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#lat
  alt:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - alt_tesim
    predicate: http://www.w3.org/2003/01/geo/wgs84_pos#alt
  place_of_publication:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - place_of_publication_tesim
    predicate: http://id.loc.gov/vocabulary/relators/pup
  owner:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    predicate: http://opaquenamespace.org/ns/hydra/owner
  on_behalf_of:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - on_behalf_of_ssim
    predicate: http://scholarsphere.psu.edu/ns#onBehalfOf
  state:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    predicate: http://fedora.info/definitions/1/0/access/ObjState#objState
  proxy_depositor:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - proxy_depositor_ssim
    predicate: http://scholarsphere.psu.edu/ns#proxyDepositor
  arkivo_checksum:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    predicate: http://scholarsphere.psu.edu/ns#arkivoChecksum
  remote_url:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - remote_url_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/uri
  advisor:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - advisor_tesim
    - advisor_sim
    predicate: http://id.loc.gov/vocabulary/relators/ths
  orcid:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - orcid_tesim
    predicate: http://id.loc.gov/vocabulary/identifiers/orcid
  date_of_award:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - date_of_award_tesim
    - date_of_award_sim
    - date_of_award_ssi
    predicate: http://purl.org/dc/terms/dateAccepted
  qualification_level:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - qualification_level_tesim
    - qualification_level_sim
    predicate: http://dlib.york.ac.uk/ontologies/uketd#qualificationLevel
  preflabel:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - preflabel_tesim
    - preflabel_si
    predicate: http://www.w3.org/2004/02/skos/core#prefLabel
  altlabel:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - altlabel_tesim
    predicate: http://www.w3.org/2004/02/skos/core#altLabel
  awarding_institution:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - awarding_institution_tesim
    - awarding_institution_sim
    predicate: http://id.loc.gov/ontologies/bibframe/grantingInstitution
  department:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - department_tesim
    - department_sim
    predicate: http://schema.org/department
  rights_description:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - rights_description_tesim
    predicate: http://purl.org/dc/elements/1.1/rights
  rights_holder:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - rights_holder_tesim
    predicate: http://purl.org/dc/terms/rightsHolder
  date:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - date_tesim
    - date_sim
    - date_ssi
    predicate: http://purl.org/dc/terms/date
  language_code:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - language_code_tesim
    predicate: http://purl.org/dc/terms/language
  qualification_name:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - qualification_name_tesim
    - qualification_name_sim
    predicate: http://dlib.york.ac.uk/ontologies/uketd#qualificationName
  rdfs_label:
    type: string
    multiple: false
    form:
      required: false
      primary: false
      multiple: false
    index_keys:
    - rdfs_label_tesim
    predicate: http://www.w3.org/2000/01/rdf-schema#label
  location:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - location_tesim
    - location_sim
    predicate: http://schema.org/location
  managing_organisation:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - managing_organisation_tesim
    - managing_organisation_sim
    predicate: http://dlib.york.ac.uk/ontologies/pure#pureManagingUnit
  note:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - note_tesim
    predicate: http://www.w3.org/2004/02/skos/core#note
  former_identifier:
    type: string
    multiple: true
    form:
      required: false
      primary: false
      multiple: true
    index_keys:
    - former_identifier_tesim
    predicate: http://dlib.york.ac.uk/ontologies/generic#formerIdentifier
