replicaCount: 2

resources:
  requests:
    memory: "4Gi"
    cpu: "1000m"
  limits:
    memory: "8Gi"
    cpu: "2000m"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: adventist.notch8.cloud
      paths:
        - path: /
    - host: "*.adventist.notch8.cloud"
      paths:
        - path: /
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: wildcard-issuer
  }
  tls:
    - hosts:
      - '*.adventist.notch8.cloud'
      - adventist.notch8.cloud
      secretName: adventist-wild-tls

extraEnvVars: &envVars
  - name: AWS_ACCESS_KEY_ID
    value: $AWS_ACCESS_KEY_ID
  - name: AWS_REGION
    value: us-east-1
  - name: AWS_S3_BUCKET
    value: space-stone-production-preprocessedbucketf21466dd-15sun4xy658nh
  - name: AWS_SECRET_ACCESS_KEY
    value: $AWS_SECRET_ACCESS_KEY
  - name: AUXILIARY_QUEUE_TENANTS
    value: sdapi
  - name: BUNDLE_BUNDLER_INJECT__GEM_PATH
    value: /app/samvera/bundler.d
  - name: BUNDLE_DISABLE_LOCAL_BRANCH_CHECK
    value: "true"
  - name: BUNDLE_LOCAL__HYKU_KNAPSACK
    value: /app/samvera
  - name: CLIENT_ADMIN_USER_EMAIL
    value: $CLIENT_ADMIN_USER_EMAIL
  - name: CLIENT_ADMIN_USER_PASSWORD
    value: $CLIENT_ADMIN_USER_PASSWORD
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/config"
  - name: DATABASE_ADAPTER
    value: postgresql
  - name: DATABASE_HOST
    value: acid-postgres-cluster-bravo.postgres.svc.cluster.local
  - name: DATABASE_NAME
    value: hyku-production-hyrax
  - name: DATABASE_USER
    value: hyku-production-hyrax
  - name: DB_ADAPTER
    value: postgresql
  - name: DB_HOST
    value: acid-postgres-cluster-bravo.postgres.svc.cluster.local
  - name: DB_NAME
    value: hyku-production-hyrax
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    value: hyku-production-hyrax
  - name: EXTERNAL_IIIF_URL
    value: https://d3pg70bdc74ala.cloudfront.net/iiif/2
  - name: FCREPO_BASE_PATH
    value: /adventist-production
  - name: FCREPO_HOST
    value: fcrepo.default.svc.cluster.local
  - name: FCREPO_PORT
    value: "8080"
  - name: FCREPO_PATH
    value: /rest
  - name: FEDORA_URL
    value: http://fcrepo.default.svc.cluster.local:8080/rest
  - name: FITS_SERVLET_URL
    value: http://fits:8080/fits
  - name: GOOD_JOB_CLEANUP_DISCARDED_JOBS
    value: "false"
  - name: GOOD_JOB_CLEANUP_PRESERVED_JOBS_BEFORE_SECONDS_AGO
    value: "604800"
  - name: GOOD_JOB_CLEANUP_INTERVAL_SECONDS
    value: "86400"
  - name: HYKU_ADMIN_HOST
    value: adventist.notch8.cloud
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: "true"
  - name: HYKU_ALLOW_SIGNUP
    value: "false"
  - name: HYKU_BULKRAX_ENABLED
    value: "true"
  - name: HYKU_CONTACT_EMAIL
    value: donotreply@adventistdigitallibrary.org
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.adventist.notch8.cloud"
  - name: HYKU_FILE_ACL
    value: "false"
  - name: HYKU_GEONAMES_USERNAME
    value: 'scientist'
  - name: HYKU_MULTITENANT
    value: "true"
  - name: HYKU_ROOT_HOST
    value: adventist.notch8.cloud
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: good_job
  - name: HYRAX_ANALYTICS
    value: "false"
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: INITIAL_ADMIN_EMAIL
    value: donotreply@adventistdigitallibrary.org
  - name: INITIAL_ADMIN_PASSWORD
    value: $INITIAL_ADMIN_PASSWORD
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: NEGATIVE_CAPTCHA_SECRET
    value: $NEGATIVE_CAPTCHA_SECRET
  - name: OMP_THREAD_LIMIT
    value: "1"
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:$REDIS_PASSWORD@adventist-knapsack-production-redis-master:6379/staging
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: adventist-knapsack-production-redis-master
  - name: REDIS_URL
    value: redis://:$REDIS_PASSWORD@adventist-knapsack-production-redis-master:6379/adventist
  - name: SECRET_KEY_BASE
    value: $SECRET_KEY_BASE
  - name: SENTRY_DSN
    value: $SENTRY_DSN
  - name: SENTRY_ENVIRONMENT
    value: "adv-knapsack-production"
  - name: SERVERLESS_ALTO_DLQ
    value: https://sqs.us-east-1.amazonaws.com/031107666127/space-stone-production-alto-xml-dlq
  - name: SERVERLESS_BATCH_SIZE
    value: "10"
  - name: SERVERLESS_COPY_DLQ
    value: https://sqs.us-east-1.amazonaws.com/031107666127/space-stone-production-copy-dlq
  - name: SERVERLESS_COPY_SQS_URL
    value: https://sqs.us-east-1.amazonaws.com/031107666127/space-stone-production-copy
  - name: SERVERLESS_COPY_URL
    value: https://3oqe2l9evk.execute-api.us-east-1.amazonaws.com/copy
  - name: SERVERLESS_OCR_DLQ
    value: https://sqs.us-east-1.amazonaws.com/031107666127/space-stone-production-ocr-dlq
  - name: SERVERLESS_OCR_SQS_URL
    value: sqs://us-east-1.amazonaws.com/031107666127/space-stone-production-ocr/
  - name: SERVERLESS_OCR_THUMB_DLQ
    value: https://sqs.us-east-1.amazonaws.com/031107666127/space-stone-production-split-ocr-thumbnail-dlq
  - name: SERVERLESS_PLAIN_TEXT_DLQ
    value: https://sqs.us-east-1.amazonaws.com/031107666127/space-stone-production-plain-text-dlq
  - name: SERVERLESS_S3_URL
    value: s3://space-stone-production-preprocessedbucketf21466dd-15sun4xy658nh.s3.us-east-1.amazonaws.com/
  - name: SERVERLESS_SPLIT_SQS_URL
    value: sqs://us-east-1.amazonaws.com/031107666127/space-stone-production-split-ocr-thumbnail/
  - name: SERVERLESS_TEMPLATE
    value: "{{dir_parts[-1..-1]}}/{{ basename }}{{ extension }}"
  - name: SERVERLESS_THUMBNAIL_DLQ
    value: https://sqs.us-east-1.amazonaws.com/031107666127/space-stone-production-thumbnail-dlq
  - name: SERVERLESS_THUMBNAIL_SQS_URL
    value: sqs://us-east-1.amazonaws.com/031107666127/space-stone-production-thumbnail/
  - name: SERVERLESS_WORD_DLQ
    value: https://sqs.us-east-1.amazonaws.com/031107666127/space-stone-production-word-coordinates-dlq
  - name: SMTP_ADDRESS
    value: mail.adventistdigitallibrary.org
  - name: SMTP_DOMAIN
    value: adventistdigitallibrary.org
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_TYPE
    value: plain
  - name: SMTP_USER_NAME
    value: donotreply@adventistdigitallibrary.org
  - name: SOLR_ADMIN_PASSWORD
    value: $SOLR_ADMIN_PASSWORD
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hyku-adventist-production
  - name: SOLR_CONFIGSET_NAME
    value: hyku-adventist-production
  - name: SOLR_HOST
    value: solr.default
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_URL
    value: http://admin:$SOLR_ADMIN_PASSWORD@solr.default:8983/solr/

worker:
  replicaCount: 1
  resources:
    requests:
      memory: "4Gi"
      cpu: "1000m"
    limits:
      memory: "8Gi"
      cpu: "2000m"
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

imagePullSecrets:
  - name: github-registry

fcrepo:
  enabled: false
postgresql:
  enabled: false
redis:
  architecture: standalone
  cluster:
    enabled: false
  password: $REDIS_PASSWORD
solr:
  enabled: false

fcrepoBasePathOverride: "/adventist-production"

externalFcrepoHost: fcrepo.default.svc.cluster.local
externalPostgresql:
  host: acid-postgres-cluster-bravo.postgres.svc.cluster.local
  username: hyku-production-hyrax
  password: $DATABASE_PASSWORD
  database: hyku-production-hyrax

externalSolrHost: solr.default.cluster.local
externalSolrUser: admin
externalSolrPassword: $SOLR_ADMIN_PASSWORD
externalSolrCollection: "hyku-adventist-production"

global:
  hyraxName: adventist-knapsack-production-hyrax

nginx:
  service:
    port: 80
  enabled: true
  image:
    registry: registry.gitlab.com
    repository: notch8/scripts/bitnami-nginx
    tag: 1.21.5-debian-10-r7
  serverBlock: |-
    upstream rails_app {
      server {{ .Values.global.hyraxName }};
    }

    map ${DOLLAR}status ${DOLLAR}loggable {
        ~^444  0;
        default 1;
    }

    log_format loki 'host=${DOLLAR}host ip=${DOLLAR}http_x_forwarded_for remote_user=${DOLLAR}remote_user [${DOLLAR}time_local] '
                      'request="${DOLLAR}request" status=${DOLLAR}status bytes=${DOLLAR}body_bytes_sent '
                      'referer="${DOLLAR}http_referer" agent="${DOLLAR}http_user_agent" request_time=${DOLLAR}request_time upstream_response_time=${DOLLAR}upstream_response_time upstream_response_length=${DOLLAR}upstream_response_length';

    error_log  /opt/bitnami/nginx/logs/error.log warn;
    #tcp_nopush     on;

    # Cloudflare ips see for refresh
    # https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs-logging-visitor-IP-addresses
    # update list https://www.cloudflare.com/ips/
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/13;
    set_real_ip_from 104.24.0.0/14;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    set_real_ip_from 2400:cb00::/32;
    set_real_ip_from 2606:4700::/32;
    set_real_ip_from 2803:f800::/32;
    set_real_ip_from 2405:b500::/32;
    set_real_ip_from 2405:8100::/32;
    set_real_ip_from 2a06:98c0::/29;
    set_real_ip_from 2c0f:f248::/32;

    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
    include /opt/bitnami/nginx/conf/conf.d/*.conf;
    server {
        listen 8080;
        server_name _;
        root /app/samvera/hyrax-webapp/public;
        index index.html;

        client_body_in_file_only clean;
        client_body_buffer_size 32K;
        client_max_body_size 0;
        access_log /opt/bitnami/nginx/logs/access.log loki;
        # if=${DOLLAR}loggable;

        sendfile on;
        send_timeout 300s;

        include /opt/bitnami/nginx/conf/bots.d/ddos.conf;
        include /opt/bitnami/nginx/conf/bots.d/blockbots.conf;

        location ~ (\.php|\.aspx|\.asp) {
        	return 404;
        }

        # deny requests for files that should never be accessed
        location ~ /\. {
          deny all;
        }

        location ~* ^.+\.(rb|log)${DOLLAR} {
          deny all;
        }

        # serve static (compiled) assets directly if they exist (for rails production)
        location ~ ^/(assets|packs|fonts|images|javascripts|stylesheets|swfs|system)/ {
          try_files ${DOLLAR}uri @rails;

          # access_log off;
          gzip_static on; # to serve pre-gzipped version

          expires max;
          add_header Cache-Control public;

          # Some browsers still send conditional-GET requests if there's a
          # Last-Modified header or an ETag header even if they haven't
          # reached the expiry date sent in the Expires header.
          add_header Last-Modified "";
          add_header ETag "";
          break;
        }

        # send non-static file requests to the app server
        location / {
          try_files ${DOLLAR}uri @rails;
        }

        location @rails {
          proxy_set_header  X-Real-IP  ${DOLLAR}remote_addr;
          proxy_set_header  X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
          proxy_set_header Host ${DOLLAR}http_host;
          proxy_redirect off;
          proxy_pass http://rails_app;
        }
    }
